### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by Annihilator708** [Annihilator708/Sebi-Machine#8]
Missing package.json
![image](https://user-images.githubusercontent.com/14298262/40381719-c57d8b10-5dfc-11e8-9984-6fad2b5791d1.png)
Also note that `/bot/package.json` is a invalid location in this project,

**Comment by Annihilator708** [comment]
json has been removed for now, please make a new folder called js and store everything you need in there so i can configure the dockerfile for you xd

**Comment by Raatty** [comment]
js is a virus anyways
